import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { ReactNode } from 'react'
import '@/styles/globals.css'


const montserrat = Montserrat( {
  variable: '--font-montserrat-sans',
  subsets: [ 'latin' ]
} )

export const metadata: Metadata = {
  title: 'Nexter',
  description: 'Generated by create next app'
}

export default function RootLayout( {
                                      children
                                    }: Readonly<{
  children: ReactNode;
}> ) {
  return (
    <html lang="en">
    <body
      className={ `${ montserrat.variable } ${ montserrat.variable } antialiased` }
    >
    { children }
    </body>
    </html>
  )
}
